--PAIS
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (1, 'Brasil');
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (2, 'Estados Unidos');
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (3, 'Canadá');
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (4, 'Alemanha');
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (5, 'Japão');

--ESTADO


--CIDADE


--BAIRRO


--ENDERECO_CLIENTE
