CREATE TABLE PAIS (
    ID_PAIS NUMBER PRIMARY KEY,
    NOME_PAIS VARCHAR2(30) NOT NULL
);

CREATE TABLE ESTADO (
    ID_ESTADO NUMBER PRIMARY KEY,
    NOME_ESTADO VARCHAR2(30) NOT NULL,
    ID_PAIS NUMBER NOT NULL,
    CONSTRAINT FK_ESTADO FOREIGN KEY (ID_PAIS) REFERENCES PAIS (ID_PAIS)
);

CREATE TABLE CIDADE (
    ID_CIDADE NUMBER PRIMARY KEY,
    NOME_CIDADE VARCHAR2(30) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    CONSTRAINT FK_CIDADE FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO (ID_ESTADO)
);

CREATE TABLE BAIRRO (
    ID_BAIRRO NUMBER PRIMARY KEY,
    NOME_BAIRRO VARCHAR2(30) NOT NULL,
    ID_CIDADE NUMBER NOT NULL,
    CONSTRAINT FK_BAIRRO FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID_CIDADE)
);

CREATE TABLE ENDERECO_CLIENTE (
    ID_ENDERECO NUMBER PRIMARY KEY,
    CEP VARCHAR2(10) NOT NULL,
    LOGRADOURO VARCHAR2(50) NOT NULL,
    NUMERO NUMBER NOT NULL,
    REFERENCIA VARCHAR2(50),
    ID_BAIRRO NUMBER NOT NULL,
    CONSTRAINT FK_ENDERECO_BAIRRO FOREIGN KEY (ID_BAIRRO) REFERENCES BAIRRO(ID_BAIRRO)
);