--PAIS
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (1, 'Brasil');
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (2, 'Estados Unidos');
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (3, 'Canadá');
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (4, 'Alemanha');
INSERT INTO PAIS (ID_PAIS, NOME_PAIS) VALUES (5, 'Japão');

--ESTADO
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, ID_PAIS) VALUES (1, 'São Paulo', 1);
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, ID_PAIS) VALUES (2, 'Rio de Janeiro', 1);
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, ID_PAIS) VALUES (3, 'Califórnia', 2);
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, ID_PAIS) VALUES (4, 'Minas Gerais', 3);
INSERT INTO ESTADO (ID_ESTADO, NOME_ESTADO, ID_PAIS) VALUES (5, 'Pernambuco', 4);

--CIDADE
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE, ID_ESTADO) VALUES (1, 'São Paulo', 1);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE, ID_ESTADO) VALUES (2, 'Rio de Janeiro', 2);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE, ID_ESTADO) VALUES (3, 'Los Angeles', 3);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE, ID_ESTADO) VALUES (4, 'Montreal', 4);
INSERT INTO CIDADE (ID_CIDADE, NOME_CIDADE, ID_ESTADO) VALUES (5, 'Munique', 5);

--BAIRRO


--ENDERECO_CLIENTE

