SET SERVEROUTPUT ON;
 
-- LOOP USANDO APENAS LOOP
 
DECLARE
    V_CONTADOR NUMBER(2):=1;
BEGIN
LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
    V_CONTADOR := V_CONTADOR + 1;
    EXIT WHEN V_CONTADOR > 20;
END LOOP;
END;
 
 
-- LOOP USANDO WHILE
DECLARE
    V_CONTADOR NUMBER(2):=1;
BEGIN
    WHILE V_CONTADOR <= 20 LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
    V_CONTADOR := V_CONTADOR + 1;
END LOOP;
END;

-- LOOP USANDO FOR
BEGIN
FOR V_CONTADOR IN 1..20 LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
END LOOP;
END;
 
-- EXERCICIO TABUADA COM LOOP
 
DECLARE
    V_TABUADA NUMBER(3) := &tabuada;
BEGIN
    FOR V_CONTADOR IN 1..10 LOOP
    DBMS_OUTPUT.PUT_LINE(V_TABUADA||' X '||V_CONTADOR||' = '||v_contador * v_tabuada);
END LOOP;
END;
 
 
DECLARE
    V_INICIO NUMBER := 1;
    V_FIM NUMBER := 152;
    QTD_PARES NUMBER := 0;
    QTD_IMPARES NUMBER := 0;
    V_CONTADOR NUMBER;
BEGIN
    FOR V_CONTADOR IN V_INICIO..V_FIM LOOP
        IF MOD (V_CONTADOR, 2) = 0 THEN
            QTD_PARES := QTD_PARES + 1;
        ELSE
            QTD_IMPARES := QTD_IMPARES +1;
        END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('Quantidade de números pares: ' || QTD_PARES);
    DBMS_OUTPUT.PUT_LINE('Quantidade de números ímpares: ' || QTD_IMPARES);
END;

@ 'C:\Users\labsfiap\Desktop\ORACLE\SCRIPT_MODELO_PEDIDO.SQL'

BEGIN
    FOR X IN (
        SELECT
            table_name
        FROM
            user_tables
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE '
                          || x.table_name
                          || ' CASCADE CONSTRAINTS';
    END LOOP;
END;

SELECT * FROM PAIS;

INSERT INTO PAIS SELECT * FROM PF1788.PAIS;
COMMIT;

INSERT INTO ESTADO SELECT * FROM PF1788.ESTADO;
COMMIT;

INSERT INTO CIDADE SELECT * FROM PF1788.CIDADE;
COMMIT;

INSERT INTO TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
COMMIT;

INSERT INTO CLIENTE SELECT * FROM PF1788.CLIENTE;
COMMIT;

INSERT INTO VENDEDOR SELECT * FROM PF1788.VENDEDOR;
COMMIT;

INSERT INTO USUARIO SELECT * FROM PF1788.USUARIO;
COMMIT;

INSERT INTO CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
COMMIT;

INSERT INTO ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
COMMIT;

INSERT INTO TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
COMMIT;

INSERT INTO PRODUTO SELECT * FROM PF1788.PRODUTO;
COMMIT;

INSERT INTO PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
COMMIT;

INSERT INTO ESTOQUE SELECT * FROM PF1788.ESTOQUE;
COMMIT;

INSERT INTO ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
COMMIT;

INSERT INTO PEDIDO SELECT * FROM PF1788.PEDIDO;
COMMIT;

INSERT INTO ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;
COMMIT;

INSERT INTO HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
COMMIT;

INSERT INTO MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
COMMIT;

ALTER TABLE CIDADE MODIFY NOM_CLIENTE VARCHAR(30);

ALTER TABLE PEDIDO ADD STATUS VARCHAR2(30);
